### ISSUE TITLE
Small probabilities beyond 16 decimal places?

### ISSUE THREAD

**Issue by nicolasdarmanthe** [tommyod/KDEpy#106]
I've noticed that the lower bound of probabilities plateaus out around 10^-16 (in both FFTKDE and Naive KDE). I think this has something to do with https://en.wikipedia.org/wiki/Decimal64_floating-point_format but am not sure how to fix.

**Comment by tommyod** [comment]
I'm not sure what a fix would mean. There's a limit to floating decimal precision. This is true for all numerical algorithms. Since a kernel density is an estimate of an unknown pdf in the first place, I don't see how more precision would help in practice. Could you tell me more about why such high resolution is useful?

**Comment by nicolasdarmanthe** [comment]
10^-16 is a small number, but not that small by computer standards? In my
use case I am very interested in the tails of the pdf. I compute the log of
the inverse pdf. In the tails, I'm getting a ceiling around 37 (=
ln(1/10^-16) ).

**Comment by tommyod** [comment]
I see. I think you should roll your own implementation then. For two reasons:

- KDEpy [adds a small constant to all outputs](https://github.com/tommyod/KDEpy/blob/c36751e5dd856202122f0b46136aadae8719afb3/KDEpy/BaseKDE.py#L213). This was done since visualization did not work well without this constant in some cases.
- If you use a kernel without finite support (e.g. Gaussian), KDEpy does a numerical computation to find a [practical value](https://github.com/tommyod/KDEpy/blob/c36751e5dd856202122f0b46136aadae8719afb3/KDEpy/kernel_funcs.py#L262).

Both of these things (and probably other numerical issues) means that KDEpy is probably not well-suited for your use case. If I were you I would probably roll my own naive implementation, placing a gaussian kernel (or whatever) on each data point and going from there.
