### ISSUE TITLE
Wrapper over plt.plot for quick plots

### ISSUE THREAD

**Issue by dafeda** [tommyod/KDEpy#19]
This is a suggestion only and might already be implemented or not wanted but here goes.

To create a kdeplot using seaborn I just need the following:

```python
import seaborn as sns
sns.kdeplot(data)
```

To do the same in KDEpy I first need to instantiate an estimator, fit some data and then plot.

Would be great to be able to do
```python
import KDEpy
KDEpy.plot(data, estimator=FFTKDE)
```

What do you think?

**Comment by tommyod** [comment]
I'm **against** this feature, since:
1. It would introduce a dependency, and a little bit more code to maintain.
2. Such a `plot` function can very easily be created by the user if they know the matplotlib and KDEpy APIs.

A one-liner is possible. Something like this works reasonably well:
```python
plt.plot(*KDEpy.FFTKDE(bw='silverman').fit(data).evaluate())
```

The argument **for** such a feature is that very often when people use FFTKDE, they compute the KDE to plot it. As such the described function would save users some time. I've thought about porting the 1D KDE to [statscollection](https://github.com/statscollection-dev/statscollection) and wrapping it in some pretty plotting functionality. Having a sub-library `statscollection.plotting` for several such functions is an idea.

**Comment by dafeda** [comment]
It does sound better to have it as a part of statscollection.
