### ISSUE TITLE
Negative weights and normalization

### ISSUE THREAD

**Issue by astrozot** [tommyod/KDEpy#22]
Dear all,

I need to compute a kernel moving average smoothing of some data. That is, given a list of `N` data `d_n` measured at the locations `x_n`, I want to evaluate
```
           \sum_{n=1}^N K(x - x_n, h) d_n
    f(x) = ------------------------------ ,
             \sum_{n=1}^N K(x - x_n, h)
```
in a set of grid-points x. To this purpose, I thought I might use KDEpy twice, once for the numerator and once for the denominator, using for the former the `d_n` as weights. I have however two main issues:
- For the numerator I need to be able to use negative weights, because in principle the data `d_n` might be negative. I can easily fix this by setting `w_n = d_n + min(d_n)`. However, looking at the code, this does not seem to be really necessary. Can you please confirm?
- The code forces the weights to be normalized to unity. I understand this is a necessary step to ensure the final result of KDE is really a PDF. In my case, though, this produces the unwanted effect to make the results wrong by a scaling factor. Again, I can easily fix this by multiplying back the result by `sum(w_n)`, but perhaps you might consider adding a keyword to prevent the forced normalization for uses similar to mine.

Best regards,
Marco

**Comment by tommyod** [comment]
Hey @astrozot . I'm letting you know that I've seen your Issue. I will respond as soon as I have some time. In the meantime, please take a look at
- [One dimensional kernel regression](https://kdepy.readthedocs.io/en/latest/examples.html#one-dimensional-kernel-regression)
in the docs. This might be useful.

**Comment by astrozot** [comment]
Dear @tommyod, thank you. As also stated in the page you indicate, the example of 1D kernel regression is not very efficient as it increases the dimensionality of the problem. Most likely, using weights is a much faster approach and scales better to higher dimensions.

**Comment by tommyod** [comment]
Dear @astrozot . Thank you again for raising this issue. I apologize for the lateness of my reply.

**Your questions first**:
1. If I recall correctly weights can be negative. I also double checked the code. I confirm.
2. Not a bad idea, I will consider adding a keyword argument to implement this functionality.

Over to the greater issue - **computing kernel regression using a kernel density estimator**.
- There are some issues with a fast implementation. The `FFTKDE` is very fast, but the KDE must be evaluated on an equidistant grid. If your data is not on an equidistant grid, then the `FFTKDE` will not work. You could preprocess the data using linear binning, and `KDEpy.binning.linbin_cython` is extremely fast. However, if not data is present in a region then this routine will set it to zero, as it's created for density estimation. This means that running such a routine on two points `(0,0)` and `(1,1)` would generate points along the `x` axis instead of points such as `(0.1, 0.1), (0.2, 0.2), ...`. A good kernel regression routine should output a linear function if given two points.
- More generally I remember looking into whether a KDE could be used efficiently for kernel regression, and the best I found was the recipe I provided [here](https://kdepy.readthedocs.io/en/latest/examples.html#one-dimensional-kernel-regression), which I already mentioned. While I'm sure more specialized implementations exist, I did notice that "_A million points should pose no problem._" in my notes.
- Are you able to create a kernel regression routine using KDEs from this library which is better than the recipe? If you solve this problem, kindly provide: (1) an algorithm sketch, (2) an algorithm in this issue or (3) a pull request - I would greatly appreciate it. If a kernel regressor can be built using the building blocks in this package I want to implemented, with your help if you have the time. :+1: 

Good luck!
