### ISSUE TITLE
Evaluation of |f^l|^2

### ISSUE THREAD

**Issue by tomicapretto** [tommyod/KDEpy#27]
Hello,

As a part of a simulation study I want to perform to compare KDE estimators I am also implementing the **Improved Sheather-Jones** method. I found your package and it is useful to compare what I did to what is actually implemented.

If we see the formula presented by Botev et. al for the computation of |f^l|^2, the constant multiplying \pi^{2j} is 0.5 and not 2. 

In his code, he also uses 2, instead of 0.5, but I think this may be a mistake.

Have you noted this issue?

`
    # Fast evaluation of |f^l|^2 using the DCT, see Plancherel theorem

    f = (
        2
        * np.pi ** (2 * ell)
        * np.sum(np.power(I_sq, ell) * a2 * np.exp(-I_sq * np.pi ** 2 * t))
    )
`

**Comment by tommyod** [comment]
Hi @tomicapretto ! 

That's very interesting. Good eye for detail! I recall that deciphering both the paper and accompanying code was challenging. It's not unlikely that I've made a mistake. If I understand you correctly, you're saying that [this line](https://github.com/tommyod/KDEpy/blob/4162b5a6ce9c3cff4a8bb42400a2398d49c5c803/KDEpy/bw_selection.py#L64) should be a 0.5 instead of a 2?

Two things must be done before I or someone else can change this:
- Look up the math. References are welcome here.
- Compute some KDEs on data with 2 vs 0.5 and look for a practial difference in the result.

I probably won't have time to look at this any time soon. If you figure out something more related to this, please post it here. PRs are also always welcome. If you're working on KDEs you might be able to improve the codebase if you do a code review in a PR. I would also like to see the results of your simulation study :+1:

Thanks again for raising the issue.

**Comment by tomicapretto** [comment]
Correct.
I had a very similar experience, it was very hard to go through the paper, the MC methods book and his code.
I am quite new to Github so I am not sure how things should be referenced. But here I try to attach a picture of the formula mentioned.
Also, I share the code I used to implement this just in case you want to compare it (it is written in R, I am translating it to python).

![image](https://user-images.githubusercontent.com/25507629/61554425-4d648c80-aa33-11e9-94aa-18d9ede54119.png)
Took from **page 327** of the book **Handbook of Monte Carlo Methods**.

[fast_kde.txt](https://github.com/tommyod/KDEpy/files/3412129/fast_kde.txt)

I will keep you posted regarding what I find related to this topic.
Thanks a lot for the response!
