### ISSUE TITLE
invalid syntax: msg = f'Kernel must be a string or callable. Options: {akernels}'

### ISSUE THREAD

**Issue by alezanalp** [tommyod/KDEpy#4]
Hi! 
Have a problem with importing, I've tried 
`from KDEpy import FFTKDE`
but have an error
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/KDEpy/__init__.py", line 5, in <module>
    from KDEpy.NaiveKDE import NaiveKDE
  File "/usr/local/lib/python3.5/dist-packages/KDEpy/NaiveKDE.py", line 11, in <module>
    from KDEpy.BaseKDE import BaseKDE
  File "/usr/local/lib/python3.5/dist-packages/KDEpy/BaseKDE.py", line 50
    msg = f'Kernel must be a string or callable. Options: {akernels}'
                                                                                                       ^
SyntaxError: invalid syntax
`

**Comment by tommyod** [comment]
Hello @alezanalp ! Thanks for reporting this. :)

Most likely it's due to your Python version not being 3.6 or 3.7. Can you run the following and check your version?
```python
import sys
print(sys.version)
```

If it is indeed the case that your version is not 3.6 or 3.7, I suggest you upgrade. I can try to backport to 3.5, as this will likely be good for other uses too -- but no promises.

**Comment by tommyod** [comment]
I didn't read your error closely enough - you're clearly on Python 3.5 (`/usr/local/lib/python3.5/dist-packages`).

Two options:
1. Try again. I've backported to Python 3.5 now, and it should hopefully work. Use `pip install --upgrade KDEpy`.
2. Upgrade to Python 3.6 og 3.7.

Let me know how it works out @alezanalp ! :+1:

**Comment by alezanalp** [comment]
@tommyod thank you, the first option worked for me!
