### ISSUE TITLE
Implement icdf method

### ISSUE THREAD

**Issue by dorukhansergin** [tommyod/KDEpy#40]
[Statsmodel's KDEUnivariate](https://www.statsmodels.org/stable/generated/statsmodels.nonparametric.kde.KDEUnivariate.html) has the method to evaluate inverse cumulative distribution function, with the signature `icdf(q)` where `q` is the quantile.

It'd be nice to have this in this great library. I'm assuming it should be easy to implement imitating the `statsmodel` implementation which is [here](https://www.statsmodels.org/stable/_modules/statsmodels/nonparametric/kde.html#KDEUnivariate.icdf).

Thank you for your consideration!

**Comment by tommyod** [comment]
Hi! I'm leaning against this, since it goes against the general API in this library. I consider a KDE to be a function, and function evaluation is done via `fit` on a grid. Computing the cdf and icdf when you have `x` and `y` is easy, but the grid is not part of the KDE object. Code to compute ICDF:

```
x, y = FFTKDE().fit(data).evaluate()

# Compute CDF
y_cdf = np.cumsum(y)
y_cdf = y_cdf / y_cdf[-1]

# Compute ICDF. Now the y is equidistant
x_icdf, y_icdf = y_cdf, x
```

**Comment by dorukhansergin** [comment]
Agreed. I guess I was just being lazy 😄. 

Thank you for the snippet by the way!

**Comment by tommyod** [comment]
No worries! :+1:
