### ISSUE TITLE
How are the grid limits estimated?

### ISSUE THREAD

**Issue by Gabriel-p** [tommyod/KDEpy#60]
I'm trying the following code:

```
import numpy as np
from KDEpy import FFTKDE

N = 100
dims = 2

xy = np.random.uniform(0., 1., (N, dims))

# Scotts rule
bw = N**(-1. / (dims + 4))

grid = FFTKDE(bw=bw, kernel='gaussian').fit(xy).evaluate(50)

print(grid[0].shape, grid[0].min(), grid[0].max())
print(grid[1].shape, grid[1].min(), grid[1].max())
```

As I understand it, `grid[0]` returns the grid, and `grid[1]` the evaluated grid. But in the example above the limits of `grid[0]` is way beyond the limits of the data.

Am I understanding something wrong here?

**Comment by tommyod** [comment]
No, you understand it correctly. I prefer calling it as `x, y = FFTE(...`, since that is more clear than indexing a `grid`variable.

You can look at the implementation to figure out how the outer points of the grid are computed. It's open source after all - looking at the code is encourage. If you think about it, it makes sense that  `x` goes "way beyond the limits of the data". The BW you compute is equivalent to approximately 0.5. The kernel you chose is gaussian. The gaussian function could be placed on zero, so you have to go far to the left of the data in order to capture the probability mass. If this is unclear, try to use a piece of paper and draw the situation.

**Comment by Gabriel-p** [comment]
I understand perfectly, thank you for the detailed explanation.

How could I use a pre-defined bounded grid in 2D? With `scipy` I define the grid as:

    xmin, xmax, ymin, ymax = 0., 1., 0., 1.
    xx, yy = np.mgrid[xmin:xmax:50j, ymin:ymax:50j]
    positions = np.vstack([xx.ravel(), yy.ravel()])

but this does not work with `KDEpy`.

**Comment by tommyod** [comment]
FFTKDE should allow a custom grid - but it must be spaced equidistantly. See the docs. If it does not work there might be a bug. If you find a bug, please post code that fails and I'll sort it out.

**Comment by Gabriel-p** [comment]
This is the grid that I've tested (which works with `scipy.stats.gaussian_kde()`):

```
import numpy as np
from KDEpy import FFTKDE

N = 100
dims = 2

xy = np.random.uniform(0., 1., (N, dims))

xmin, xmax, ymin, ymax = 0., 1., 0., 1.
xx, yy = np.mgrid[xmin:xmax:50j, ymin:ymax:50j]
positions = np.vstack([xx.ravel(), yy.ravel()])

# Scotts rule
bw = N**(-1. / (dims + 4))
grid, points = FFTKDE(bw=bw, kernel='gaussian').fit(xy).evaluate(positions)
```

which fails with:

```
  File "KDEpy/cutils.pyx", line 412, in cutils.grid_is_sorted
  File "KDEpy/cutils.pyx", line 406, in cutils.grid_is_sorted
  File "KDEpy/cutils.pyx", line 412, in cutils.grid_is_sorted
  File "KDEpy/cutils.pyx", line 412, in cutils.grid_is_sorted
  File "KDEpy/cutils.pyx", line 412, in cutils.grid_is_sorted
  [Previous line repeated 992 more times]
  File "KDEpy/cutils.pyx", line 354, in cutils.grid_is_sorted
  File "stringsource", line 1009, in View.MemoryView.memoryview_fromslice
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by tommyod** [comment]
Your grid is the wrong shape, use `positions = np.vstack([xx.ravel(), yy.ravel()]).T` instead.

Also, when you supply a grid, only the points are returned, so use `points = FFTKDE(bw=bw, ...`.

Hope this helps.
