### ISSUE TITLE
New machine, now cannot replicate KDEpy KDE's in scientific paper in review.

### ISSUE THREAD

**Issue by chrisrmaupin** [tommyod/KDEpy#85]
KDEpy is cited in the paper, but I am **extremely** alarmed that the identical data and code no longer generate the same plots (originally made in 2019), which is critical for a core interpretation of the paper. Here is an example. It appears to have become over-smoothed/weights are no longer working as they were. 

This code generated the first plot on a 2019 environment (and in the paper), now it generates the second more smoothed version. Please help. 

data_all = np.array(df['value'])
weights_all = np.array(df['wgt'])
x, y = FFTKDE(kernel='gaussian', bw='ISJ').fit(data_all, weights=weights_all).evaluate()
xb, yb = FFTKDE(kernel='box', bw='ISJ').fit(data_all, weights=weights_all).evaluate()
plt.scatter(data_all, np.zeros_like(data_all), marker='|', color=c_kde)
plt.plot(xb, yb, color=c_kde); plt.tight_layout()
plt.plot(x, y, color=c_kde); plt.tight_layout()
<img width="425" alt="Testold" src="https://user-images.githubusercontent.com/50376605/104886714-cd70f880-592f-11eb-9a59-ec47203cbef7.png">
<img width="425" alt="testnew" src="https://user-images.githubusercontent.com/50376605/104886718-d06be900-592f-11eb-8dc0-da3bc2cadada.png">

**Comment by tommyod** [comment]
I'm pretty sure I know the reason. The "ISJ" implementation contained a bug, which was fixed in May 2020. The author of the ISJ algorithm had the same bug in his matlab implementation, but it was pointed out in [this issue](https://github.com/tommyod/KDEpy/issues/27), fixed in [this commit](https://github.com/tommyod/KDEpy/commit/966d13cb9897308af9aa747e83f0e36a960f7627). If you run the code with the same KDEpy version as you did in 2019, it should produce the same result.

I'm sorry for any inconvenience this has caused you.

**Comment by tommyod** [comment]
Resolved. The inconsistency was due to the 1.0.4 -> 1.0.5 bugfix.
